name: Deploy Secrets

on:
  push:
      paths: 
          - 'secrets/**'
      branches:
          - main
  workflow_dispatch:

jobs:
    deploy-secrets:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Load Secrets using SLV
          uses: amagioss/slv-action@main
          with:
            vault: deploy/deploy.slv.yaml
            env-secret-key: ${{ secrets.SLV_ENV_SECRET_KEY }}
            prefix: "SECRETS_DEPLOY_"
        - name: Copy SLV K8s Secrets to Remote Server
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{ env.SECRETS_DEPLOY_HOST }}
            username: ${{ env.SECRETS_DEPLOY_USER }}
            key: ${{ env.SECRETS_DEPLOY_SSH_PRIVATE_KEY }}
            source: "secrets"
            target: "~/"
        - name: Deploy SLV Secrets
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ env.SECRETS_DEPLOY_HOST }}
            username: ${{ env.SECRETS_DEPLOY_USER }}
            key: ${{ env.SECRETS_DEPLOY_SSH_PRIVATE_KEY }}
            script: |
                kubectl apply -f secrets
                rm -rf secrets
